name: Build and Push Docker Image

on:
  push:
    branches:
      - dev  # Runs on main branch updates

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Ubuntu VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch latest code

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Authenticate with Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/account-tracker:DEV .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/account-tracker:DEV

      # look into this in the future for automated version updates
      # - name: Create Git Tag for New Version
      #   run: |
      #     git tag $NEW_VERSION
      #     git push origin $NEW_VERSION
