name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs on main branch updates

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Ubuntu VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch latest code

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Authenticate with Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Latest Version & Increment
        id: versioning
        run: |
          latest_version=$(git tag --sort=-v:refname | head -n 1 | tr -d '[:space:]')
          if [[ -z "$latest_version" ]]; then
            latest_version="2.2.0"
          fi
          IFS='.' read -r major minor patch <<< "$latest_version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          echo "New version: $new_version"

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/account-tracker:$NEW_VERSION .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/account-tracker:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/account-tracker:$NEW_VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/account-tracker:latest

      # look into this in the future for automated version updates
      # - name: Create Git Tag for New Version
      #   run: |
      #     git tag $NEW_VERSION
      #     git push origin $NEW_VERSION
