name: Build and Push Docker Image  # 1️⃣ Workflow name

on:
  push:
    branches:
      - main  # 2️⃣ This workflow triggers when changes are pushed to the main branch.

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 3️⃣ Runs on a Linux-based virtual machine (Ubuntu)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 4️⃣ Fetches the latest code from the repository

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # 5️⃣ Logs into Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 6️⃣ Uses GitHub secret for Docker username
          password: ${{ secrets.DOCKER_PASSWORD }}  # 7️⃣ Uses GitHub secret for Docker password/token

      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/your-image-name:1.2.1 .  # 8️⃣ Builds a Docker image with the latest code

      - name: Push Docker Image to Docker Hub
        run: |
          docker push your-dockerhub-username/your-image-name:1.2.1  # 9️⃣ Pushes the image to Docker Hub
