name: Build and Push Docker Image  # CI/CD Workflow

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Ubuntu virtual machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch latest code

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Authenticate with Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Latest Version & Increment
        id: versioning
        run: |
          latest_version=$(git tag --sort=-v:refname | head -n 1 || echo "1.0.0")
          major=$(echo $latest_version | cut -d. -f1)
          minor=$(echo $latest_version | cut -d. -f2)
          patch=$(echo $latest_version | cut -d. -f3)
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          echo "New version: $new_version"

      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/your-image-name:$NEW_VERSION .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push your-dockerhub-username/your-image-name:$NEW_VERSION

      - name: Create Git Tag for New Version
        run: |
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
